In [40]:
import numpy as np
from statistics import mode
import matplotlib.pyplot as ptl

# A measure of central tendency (also referred to as measures of centre or central location) 
# is a summary measure that attempts to describe a whole set of data with a single value that 
# represents the middle or centre of its distribution.

# There are three main measures of central tendency: the mode, the median and the mean. 
# Each of these measures describes a different indication 
# of the typical or central value in the distribution.

In [41]:
m = np.random.randint(7,10,20)
print(m)

[8 8 8 7 8 8 9 9 9 7 8 7 8 7 9 7 8 8 8 8]


In [42]:
# mean
# def mean(x):
#     return sum(x) / len(x)

np.mean(m)

7.95

In [43]:
# mediam
# the middle value in distribution 
np.median(m)


8.0

In [44]:
# mode
# the most commonly occurring value in a distribution
mode(m)

8

In [45]:
# Population
population = np.random.randint(10, 20, 100)
population

array([19, 12, 17, 12, 15, 13, 15, 10, 16, 17, 13, 16, 19, 10, 15, 17, 11,
       11, 15, 19, 13, 13, 13, 15, 12, 15, 14, 18, 17, 19, 16, 19, 11, 12,
       11, 10, 18, 18, 19, 16, 19, 11, 13, 19, 17, 15, 14, 12, 10, 17, 15,
       11, 11, 17, 12, 10, 10, 10, 17, 11, 10, 13, 18, 16, 14, 15, 12, 12,
       10, 11, 15, 18, 10, 15, 19, 19, 14, 19, 15, 16, 16, 15, 11, 10, 17,
       17, 12, 16, 10, 13, 10, 15, 14, 13, 12, 10, 12, 17, 18, 17])

In [46]:
# mean population
np.mean(population)

14.28

In [47]:
# median
a = [1,2,3,4,5,6,7,7,6,5,4,3,2,1]
mode(a)
np.median(a)

4.0

In [48]:
# mediam population
np.median(population)

15.0

In [49]:
# mode population
mode(population)

15

In [50]:
sample = np.random.choice(population, 20)
sample

array([15, 14, 17, 18, 15, 19, 15, 13, 11, 11, 16, 16, 15, 17, 11, 18, 13,
       18, 15, 19])

In [51]:
# print all variables
print(np.mean(sample))
print(np.median(sample))
print(mode(sample))

15.3
15.0
15


In [52]:
sample1 = np.random.choice(population, 15)
sample2 = np.random.choice(population, 15)
sample3 = np.random.choice(population, 15)
sample4 = np.random.choice(population, 15)

In [53]:
# join examples
all_samples = [sample1, sample2, sample3, sample4]
sample_mean = []
for i in all_samples:
    sample_mean.append(np.mean(i))

sample_mean

[14.4, 16.133333333333333, 13.8, 13.8]