In [14]:
# Spread: Propagacion.
# Measures of spread describe how similar or varied the set of observed 
# values are for a particular variable (data item). Measures of spread include the range, 
# quartiles and the interquartile range, variance and standard deviation.

import numpy as np
from statistics import mode
import matplotlib.pyplot as ptl

In [15]:
n = np.random.randint(1,10,30)
n

array([6, 3, 1, 3, 9, 9, 4, 2, 9, 8, 7, 7, 6, 2, 1, 3, 3, 1, 4, 4, 9, 2,
       6, 4, 5, 4, 1, 2, 2, 3])

In [16]:
# range
np.max(n) - np.min(n)

8

In [17]:
# quartiles
print("first quartile - Q1", np.percentile(n,25))
print("second quartile - Q2",np.percentile(n,50))
print("third quartile - Q3 ",np.percentile(n,75))
print("Inter quartile", np.percentile(n,75)-np.percentile(n,25))

first quartile - Q1 2.0
second quartile - Q2 4.0
third quartile - Q3  6.0
Inter quartile 4.0


In [18]:
population = np.random.randn(100)
population

array([-1.11327895, -2.93348354,  0.71262088,  0.97698099,  0.899451  ,
        2.13463312,  1.64076697,  0.393133  ,  0.23054993, -1.66275579,
        0.59190688, -0.32712332, -0.20400067, -1.52161767, -0.19197777,
       -0.59646156,  0.14811473,  0.59681127, -0.31038946, -0.82054493,
       -1.22976641,  0.48556205,  0.40129407, -0.12201537, -0.55396487,
        0.29907397,  0.60562742,  0.83844495,  0.92006585,  0.63990054,
        0.50895163, -0.05209328, -1.11721014,  1.05206265,  0.39885927,
        2.19373943, -0.857423  , -0.77859035, -0.10145695, -0.06946547,
       -0.21026687,  0.48981305,  1.10808344,  0.03157548,  2.38683678,
        0.5041394 , -2.50799868, -0.87313746,  0.7425017 , -0.32165791,
       -0.79174179,  0.65613331,  0.61255444, -1.49312813,  0.38855438,
       -0.52120401,  0.59968656, -0.09288002, -1.39947423,  0.79708873,
       -1.94435738, -1.68011242, -0.46048853,  0.5705739 ,  0.84001307,
        0.89762315, -0.23692159, -0.52486299, -2.33560894, -1.41

In [19]:
sample = np.random.choice(population, 20)
sample

array([ 0.41328829,  0.23054993,  1.48091972,  0.59190688, -0.37283104,
       -0.46048853, -0.19197777,  0.79708873,  0.7425017 ,  1.26623959,
        0.48981305,  0.5705739 , -0.31038946,  1.48091972, -2.50799868,
        0.83844495,  0.40129407, -0.60481518,  1.03037858,  0.84416895])

In [21]:
# variance
np.var(population)

1.1361670382733373

In [22]:
# variance
np.var(sample)

0.7915061644836711

In [25]:
# Let’s calculate the variance of the follow data set: 2, 7, 3, 12, 9.
# The first step is to calculate the mean. The sum is 33 and there are 5 data points. 
# Therefore, the mean is 33 ÷ 5 = 6.6. Then you take each value in data set, subtract the mean 
# and square the difference. For instance, for the first value:
# (2 - 6.6)2  = 21.16
# The squared differences for all values are added:
# 21.16 + 0.16 + 12.96 + 29.16 + 5.76 = 69.20
# The sum is then divided by the number of data points:
# 69.20 ÷5 = 13.84
# The variance is 13.84. To get the standard deviation, you calculate the square 
# root of the variance, which is 3.72.

v = [2, 7, 3, 12, 9]
print("the mean is:", np.mean(v))
print("the variance is:", np.var(v))
print("the standard deviation is:", np.std(v))

the mean is: 6.6
the variance is: 13.84
the standard deviation is: 3.7202150475476548


In [28]:
# standart deviation
print("the variance is: ", np.var(population))
print("the standard deviation is: ", np.std(population))

the variance is:  1.1361670382733373
the standard deviation is:  1.0659113651112542
