In [1]:
import numpy as np

In [2]:
x = np.array([x for x in range(10)])

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.where(x%2==0, 'Even', 'Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [10]:
condlist    = [x<5,x>5]
choicelist  = [x**2,x**3]

In [12]:
condlist

[array([ True,  True,  True,  True,  True, False, False, False, False,
        False]),
 array([False, False, False, False, False, False,  True,  True,  True,
         True])]

In [13]:
choicelist

[array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]),
 array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])]

In [11]:
np.select(condlist,choicelist, default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])