In [1]:
import numpy as np

In [2]:
np.ndarray(24)

array([1.50464254e-316, 0.00000000e+000, 6.95061049e-310, 6.95061049e-310,
       6.95061049e-310, 6.95061049e-310, 6.95061049e-310, 6.95061049e-310,
       6.95061049e-310, 6.95061049e-310, 6.95061049e-310, 6.95061049e-310,
       6.95061049e-310, 6.95061049e-310, 6.95061049e-310, 6.95061049e-310,
       6.95061049e-310, 6.95061049e-310, 6.95061049e-310, 6.95061049e-310,
       6.95061049e-310, 6.95061049e-310, 6.95061049e-310, 6.95061049e-310])

In [3]:
np.array(24)

array(24)

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
np.array([[1,1,1],[1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [11]:
numpy_arr =np.array([[[1,1,1],[1,2,1]],[[2,2,3],[4,5,4]]])

In [12]:
numpy_arr.shape

(2, 2, 3)

In [13]:
numpy_arr.ndim

3

In [14]:
np_arr = np.array([x for x in range(1,10)])

In [15]:
np_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np_arr = np.array([x for x in range(1,13)])

In [18]:
np_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
np_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [20]:
np_arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
np_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
np_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##### operation arrays

In [23]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

In [24]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [26]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [27]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [28]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [29]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]])