In [17]:
import numpy as np

In [18]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])

In [19]:
array_1d[0]

1

In [20]:
array_1d[1]

2

In [21]:
array_1d[-3]

4

In [22]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_2d[0,0]

1

In [24]:
array_2d[0,1]

2

In [25]:
array_2d[0,-1]

3

In [26]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
array_3d[0,2,2]

9

In [29]:
array_3d[0,1,1]

5

In [30]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [31]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [35]:
array_1d[2]

3

In [36]:
array_1d[3:5]

array([4, 5])

In [37]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
array_2d[1,1:]

array([5, 6])

In [41]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

In [42]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
array_3d[0,1:,1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])