In [1]:
import numpy as np

In [2]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [3]:
np.amin(arr)

0

In [4]:
np.amin(arr, axis=0)

array([4, 1, 0])

In [5]:
np.amin(arr, axis=1)

array([2, 0, 5])

In [6]:
np.max(arr)

24

In [7]:
np.amax(arr,axis=0)

array([10,  8, 24])

In [8]:
np_array_2d = np.arange(0, 6).reshape([2,3])

In [9]:
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
np.sum(np_array_2d, axis = 0)

array([3, 5, 7])

In [11]:
np.sum(np_array_2d, axis = 1)

array([ 3, 12])

In [14]:
np.median(arr)

4.0

In [15]:
np.mean(arr)

6.333333333333333

In [16]:
np.std(arr)

6.944222218666553

In [17]:
np.var(arr)

48.22222222222222

In [19]:
np.percentile(arr,50)

4.0