Module 5: Introduction to NumPy


1. Convert the given list into a numpy array and replace the odd elements with -2.


In [34]:
import numpy as np
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# type(lst)
npLst = np.array(lst)  # to do more efficiently
np.where(npLst % 2 != 0, -2, npLst)  # and apply the method where


array([[-2,  2, -2],
       [ 4, -2,  6],
       [-2,  8, -2]])

2. In the numpy array given below print all the elements ranging from 8 to 15


In [46]:
arr = [1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7]
npArr = np.array(arr)
# Extract the indices where the value is between 8 and 15
res = np.where((npArr >= 8) & (npArr <= 15))
print(npArr[res])  # Print the indices where the value is between 8 and 15


[ 8  9 10 12]


3. Create a 3\*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2.


In [57]:
arr = np.arange(9).reshape(3, 3)
print(arr)
print('*' * 20)
arr[:, [1, 0]] = arr[:, [0, 1]]  # Interchange rows and columns
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
********************
[[1 0 2]
 [4 3 5]
 [7 6 8]]


4. In the given numpy array replace the NaN values with the average of columns


In [65]:
arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the mean by column
col_mean = np.nanmean(arr, axis=0)
# Find the indices of the column with nan values
indices = np.where(np.isnan(arr))
# replace the nan values with the column mean
arr[indices] = np.take(col_mean, indices[1])
print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


5. For the numpy array given below perform the following operation:


In [71]:
arr = [[2, 4, 6],
       [1, 3, 5]]

# i.Convert the numpy array into a numpy matrix
m = np.asmatrix(arr)
print(m)
print('*' * 20)
# ii.Sort the values in a matrix
m.sort(axis=0)
print(m)


[[2 4 6]
 [1 3 5]]
********************
[[1 3 5]
 [2 4 6]]
