# Numpy Real world applications

In [1]:
'''
Why NumPy?
Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make 
working with ndarray very easy.

Applications -
1. Financial functions
2. Linear Algebra
3. Statistics
4. Polynomials
5. Sorting, searching etc.

Mainly used by institutions like - NASA and in Oceanography
http://ui.adsabs.harvard.edu/abs/2020Natur.585..357H/abstract

For example, in astronomy, NumPy was an important part of the software stack used in the discovery of 
gravitational waves1 and in the first imaging of a black hole2.
'''

'\nWhy NumPy?\nWhy Use NumPy?\nIn Python we have lists that serve the purpose of arrays, but they are slow to process.\nNumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\nThe array object in NumPy is called ndarray, it provides a lot of supporting functions that make \nworking with ndarray very easy.\n\nApplications -\n1. Financial functions\n2. Linear Algebra\n3. Statistics\n4. Polynomials\n5. Sorting, searching etc.\n\nMainly used by institutions like - NASA and in Oceanography\nhttp://ui.adsabs.harvard.edu/abs/2020Natur.585..357H/abstract\n\nFor example, in astronomy, NumPy was an important part of the software stack used in the discovery of \ngravitational waves1 and in the first imaging of a black hole2.\n'

### installing numpy as it is an external library
### when using command prompt --> pip install numpy
### when installing from jupyter notebook --> ! pip install numpy

In [2]:
# list vs numpy comparision with respect to speed
# ms is millisecond
L = list(range(100000))
print(type(L))
%timeit sum_val = sum(L)

<class 'list'>
899 µs ± 12.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
'''
%timeit - Time execution of a Python statement or expression
'''

'\n%timeit - Time execution of a Python statement or expression\n'

In [4]:
# Reason why it is fast is because of homogeneity (the quality or state of being all the same or all of the same kind)
# Optimization is easy as all data types are same.
# µs is microsecond
import numpy as np
numpy_L = np.arange(100000)
%timeit sum_val = np.sum(numpy_L)

23.4 µs ± 377 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Numpy code examples

In [59]:
# Creating numpy arrays of 1-D, 2-D and 3-D dimensions
# Syntax : numpy.array([list of numbers])

import numpy as np
x = np.array([100,200,300])
print("1-D array")
print(type(x))
print(x)
print(x[2])

1-D array
<class 'numpy.ndarray'>
[100 200 300]
300


In [6]:
print("Number of axes in the array (x.ndim):", x.ndim) # provides the number of axes in the array

Number of axes in the array (x.ndim): 1


In [7]:
# results into a tuple of integers indicating the size of the array in each dimension
print("Results into a tuple of integers indicating the size of the array (x.shape):", x.shape)

Results into a tuple of integers indicating the size of the array (x.shape): (3,)


In [8]:
# Gives the type of the elements in the array
print("Gives the type of the elements in the array (x.dtype):", x.dtype) 

Gives the type of the elements in the array (x.dtype): int32


In [9]:
# provides the total number of elements in the array
print("Provides the total number of elements in the array (x.size):", x.size) 

Provides the total number of elements in the array (x.size): 3


In [10]:
# provides the size in bytes of each element of the array
print("Provides the size in bytes of each element of the array (x.itemsize):", x.itemsize) 

Provides the size in bytes of each element of the array (x.itemsize): 4


### 2-D Array

In [61]:
# Creating a 2D array using collection of arrays

L = [[1,2,3], [4,5,6]]
arr = np.array(L)
print('Array creating using a list or existing data')
print(arr)
print("Number of axes in the array:", arr.ndim) # provides the number of axes in the array
print("Shape of the array:", arr.shape)
print("Size of the array:", arr.size)

Array creating using a list or existing data
[[1 2 3]
 [4 5 6]]
Number of axes in the array: 2
Shape of the array: (2, 3)
Size of the array: 6


In [62]:
L = [[0,0], [0,0]]
arr = np.array(L)
print(arr)

[[0 0]
 [0 0]]


In [63]:
L = [[1,1], [1,1]]
arr = np.array(L)
print(arr)

[[1 1]
 [1 1]]


In [12]:
# Different ways of creating numpy array
# In programs we use to initalize a counter to zero, here we use these fns for initialization of the array
# using zeros function
import numpy as np
arr = np.zeros([2,2])
print('Array created using zeros function')
print(arr)

# using ones function
arr = np.ones([3,3])
print('Array created using ones function')
print(arr)

Array created using zeros function
[[0. 0.]
 [0. 0.]]
Array created using ones function
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### using copy function

In [65]:
arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = arr1.copy()

print('Array created using copy function')
print("arr1:")
print(arr1)
print()

print("arr2:")
print(arr2)

Array created using copy function
arr1:
[[1 2 3]
 [4 5 6]]

arr2:
[[1 2 3]
 [4 5 6]]


In [66]:
# ARRAYNAME[ROWINDEX][COLUMNINDEX]
print(arr2[1][0])

arr2[1][0] = 1900
arr2[0][2] = 2900

print("arr1:", arr1)
print()
print("arr2:", arr2)

4
arr1: [[1 2 3]
 [4 5 6]]

arr2: [[   1    2 2900]
 [1900    5    6]]


### using arange function

In [67]:
# syntax: range(start, end+1, steps)
# by detault steps = 1
import numpy as np
arr = np.arange(0, 20, 2)
print('Array created using arange function')
print(arr)

# using linspace function . Break 0 - 10 in (3-1) equal parts
arr = np.linspace(0, 10, 3)
print('Array created using linspace function')
print(arr)

Array created using arange function
[ 0  2  4  6  8 10 12 14 16 18]
Array created using linspace function
[ 0.  5. 10.]


### Arithmetic operations on numpy arrays

In [68]:
arr = np.arange(10)
print("Array:")
print(arr)

print("Element wise arithmetic operations")
print("Add 2 to each element of the array:", arr+2)
print("Sub 2 from each element of the array:", arr-2)
print("Mult 2 to each element of the array:", arr*2)
print("Div by 2 each element of the array:", arr/2)
print("Div 2 to each element of the array to get the quotient:", arr//2)
print("Square each element of the array:", arr**2)

Array:
[0 1 2 3 4 5 6 7 8 9]
Element wise arithmetic operations
Add 2 to each element of the array: [ 2  3  4  5  6  7  8  9 10 11]
Sub 2 from each element of the array: [-2 -1  0  1  2  3  4  5  6  7]
Mult 2 to each element of the array: [ 0  2  4  6  8 10 12 14 16 18]
Div by 2 each element of the array: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Div 2 to each element of the array to get the quotient: [0 0 1 1 2 2 3 3 4 4]
Square each element of the array: [ 0  1  4  9 16 25 36 49 64 81]


In [17]:
arr = np.arange(10)
print(arr)
arr2 = arr + 2
print(arr2)
arr2[9] = arr2[3] + 3
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10  8]


In [18]:
# Arithmetic operations on two 1-D arrays

arr1 = np.arange(5)
arr2 = np.arange(6,11)

print("array1:")
print(arr1)
print("array2:")
print(arr2)
print("Arithmetic operations")
print("Add", arr1+arr2)
print("Sub", arr1-arr2)
print("Multiply", arr1*arr2)
print("Divide", arr1/arr2)
print("Power", arr1**arr2)

array1:
[0 1 2 3 4]
array2:
[ 6  7  8  9 10]
Arithmetic operations
Add [ 6  8 10 12 14]
Sub [-6 -6 -6 -6 -6]
Multiply [ 0  7 16 27 40]
Divide [0.         0.14285714 0.25       0.33333333 0.4       ]
Raised to [      0       1     256   19683 1048576]


### Reshape Function

In [19]:
arr1 = np.arange(15)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [69]:
arr1 = np.arange(15).reshape(3,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [70]:
arr1[1][3]

8

In [21]:
# Arithmetic operations on two 2-D arrays
# reshape function
arr1 = np.arange(9).reshape(3,3)
arr2 = np.ones([3,3])

print("array1")
print(arr1)
print("array2")
print(arr2)
print("Arithmetic operations")
print("Add", arr1+arr2)
print("Sub", arr1-arr2)
print("Multiply", arr1*arr2)

array1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
array2
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arithmetic operations
Add [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Sub [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Multiply [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [71]:
# Matric multiplication or dot product
# Matrix multiplication rule: the number of columns in first matrix must be equal to number of rows in the second matrix

arr1 = np.arange(4).reshape(2,2)
arr2 = np.ones([2,2])
arr2 = arr2 * 2

print("array1")
print(arr1)
print("array2")
print(arr2)

print("matrix multiplication element wise operation")
print(arr1+arr2)
print(arr1*arr2)

array1
[[0 1]
 [2 3]]
array2
[[2. 2.]
 [2. 2.]]
matrix multiplication element wise operation
[[2. 3.]
 [4. 5.]]


In [23]:
# Matrix Product: the dot method (show in excel)

a = np.arange(4).reshape(2,2)
print("A = \n", a)
b = np.array([[11,12],[13,14]]) 
print("B = \n", b)
np.dot(a,b)

A = 
 [[0 1]
 [2 3]]
B = 
 [[11 12]
 [13 14]]


array([[13, 14],
       [61, 66]])

In [24]:
# Universal functions - https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations
# Universal functions - Arithmetic or Math functions

arr1 = np.arange(4).reshape(2,2)
arr2 = np.array([[1,2],[3,4]])

print("Array1")
print(arr1)
print("Array2")
print(arr2)
print("Universal Math functions")
print("Add : ", np.add(arr1, arr2)) # arr1+arr2
print("Sub : ", np.subtract(arr1, arr2)) # arr1 - arr2
print("Divide : ", np.divide(arr2, arr1)) # arr2 / arr1
print("Multiply : ", np.multiply(arr1, arr2)) # arr1 * arr2
print("Power : ", np.power(arr1, arr2)) # arr1 ** arr2

print("Sq Root of arr1: \n", np.sqrt(arr1))
print("Log : ", np.log(arr2))

arr3 = np.array([[16, 25],[9, 4]])
print("Array3")
print(arr3)
print("Sq Root of arr3: \n", np.sqrt(arr3))

Array1
[[0 1]
 [2 3]]
Array2
[[1 2]
 [3 4]]
Universal Math functions
Add :  [[1 3]
 [5 7]]
Sub :  [[-1 -1]
 [-1 -1]]
Divide :  [[       inf 2.        ]
 [1.5        1.33333333]]
Multiply :  [[ 0  2]
 [ 6 12]]
Power :  [[ 0  1]
 [ 8 81]]
Sq Root of arr1: 
 [[0.         1.        ]
 [1.41421356 1.73205081]]
Log :  [[0.         0.69314718]
 [1.09861229 1.38629436]]
Array3
[[16 25]
 [ 9  4]]
Sq Root of arr3: 
 [[4. 5.]
 [3. 2.]]


C:\Users\knsab\AppData\Local\Temp\ipykernel_9840\521639821.py:14: RuntimeWarning: divide by zero encountered in divide
  print("Divide : ", np.divide(arr2, arr1)) # arr2 / arr1


In [25]:
# Universal functions - Trigonometric functions

arr1 = np.arange(4).reshape(2,2)

print("Array1")
print(arr1)
print("Universal Trigonometric functions")
print(np.sin(arr1))
print(np.cos(arr1))
print(np.tan(arr1))

Array1
[[0 1]
 [2 3]]
Universal Trigonometric functions
[[0.         0.84147098]
 [0.90929743 0.14112001]]
[[ 1.          0.54030231]
 [-0.41614684 -0.9899925 ]]
[[ 0.          1.55740772]
 [-2.18503986 -0.14254654]]


In [74]:
# Universal functions - Comparision functions
# comparision functions always result with True or False values. 

arr1 = np.array([1, 4, 3])
arr2 = np.array([3, 4, 5])

print("Array1", arr1)
print("Array2", arr2)
print("Universal Comparison functions")
print(np.greater(arr1, arr2)) # >
print(np.greater_equal(arr1, arr2)) # >=
print(np.less(arr1, arr2)) # <
print(np.less_equal(arr1, arr2)) # <= 
print(np.equal(arr1, arr2)) # ==
print(np.not_equal(arr1, arr2)) # !=

Array1 [1 4 3]
Array2 [3 4 5]
Universal Comparison functions
[False False False]
[False  True False]
[ True False  True]
[ True  True  True]
[False  True False]
[ True False  True]


In [27]:
# Universal functions - mod()
# Explaination - It returns element-wise remainder of division between two array arr1 and arr2 
# i.e. arr1 % arr2 .It returns 0 when arr2 is 0 and both arr1 and arr2 are (arrays of) integers.

import numpy as np
x = np.mod(6,4) # 6/4 = Q = 1 R = 2
print(x)

x = np.mod(np.arange(7),5) # = (0/5, 1/5, 2/5, 3/5, 4/5, 5/5, 6/5)
print(x)

2
[0 1 2 3 4 0 1]


In [28]:
# Universal functions - log()
# Explaination

import numpy as np
x = np.log([1,np.e,0])
print(x)

[  0.   1. -inf]


C:\Users\knsab\AppData\Local\Temp\ipykernel_9840\1907883935.py:5: RuntimeWarning: divide by zero encountered in log
  x = np.log([1,np.e,0])


In [29]:
import numpy as np
Base = 3
Height = 4
Hypotenuse = np.hypot(Base, Height)
print(Hypotenuse)

5.0


In [30]:
# Aggregate functions - https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html
import numpy as np

arr = np.arange(1,10)
print("Array:", arr)

print("Aggregate functions")
print("Sum:",arr.sum())
print("Mean:",arr.mean()) # sum divide by number of values = 45/9
print("Min:",arr.min())
print("Max:",arr.max())

Array: [1 2 3 4 5 6 7 8 9]
Aggregate functions
Sum: 45
Mean: 5.0
Min: 1
Max: 9


In [76]:
# Logic functions - Testing Truth value
# all => if all the elements are true then the resultant will be true
# any => if any of the elements are true then the resultant will be true
# numpy.all(array, axis = None, out = None, keepdims = <NoValue>)

import numpy as np

print("All function examples")
x = [[False,True],[True,True]]

print("2d-Array:", np.array(x))
print()
print("Result:")
np.all((x))

All function examples
2d-Array: [[False  True]
 [ True  True]]

Result:


False

In [32]:
# Any Logic fucntion - show explaination in excel
# axis 0 checks columnswise where as axis =1 checks rowwise 

print(np.any([[False,False],[True,True]], axis=0))

[ True  True]


In [33]:
# Logic functions - Testing Array Type

# complex number: a + ij
print(np.iscomplex([2+1j, 3+5j, 4+8j, 4, 5 + 0j, 6.5]))
print(np.isreal([1,2,3.5,2+1j])) # by default numbers stored are float => 1 -> 1.0

[ True  True  True False False False]
[ True  True  True False]


In [77]:
# Indexing on 1-d, 2-d

import numpy as np

# indexing on 1 dimensional array
arr = np.array([11,12,13,14,15])
# index =        0  1  2  3  4

print("1-D array")
print("-"*10)
print("arr :", arr)
print("Index 2:", arr[2])
print("Index -5:", arr[-5])
print("Index 4:", arr[len(arr)-1]) # same as above statement

1-D array
----------
arr : [11 12 13 14 15]
Index 2: 13
Index -5: 11
Index 4: 15


In [78]:
# indexing on 2 dimensional array
arr = np.arange(9).reshape(3,3)
print("2-D array")
print("-"*10)
print(arr)
# Syntax arrayname[row index][column index]
print(arr[1,1])
print(arr[2][2]) # same as above statement

2-D array
----------
[[0 1 2]
 [3 4 5]
 [6 7 8]]
4
8


In [81]:
# Fancy Indexing - Slide 52
# Values:  3,78,23,12,90,10,45,56
# Indexes: 0, 1, 2, 3, 4, 5, 6, 7

import numpy as np
a = np.array([3,78,23,12,90,10,45,56])
ind = np.array([[3,5],[2,4]])
print(a[ind])
b = a[ind]

[[12 10]
 [23 90]]


In [82]:
b[0][0]

12

In [89]:
# Slicing 1-D array

import numpy as np 

arr = np.arange(21,31)
print('Original array: ', arr)

print('1-D Slicing operations')
print(arr[5:9:2]) # same as above statement
print()

Original array:  [21 22 23 24 25 26 27 28 29 30]
1-D Slicing operations
[26 28]



In [92]:
import numpy as np 

# slicing on 2-d array
arr = np.array([np.arange(5), np.arange(6,11)])
print('Original 2d array:')
print(arr)
print('Multi-Dimensional Slicing operations')
print(arr[0:1, 0:2]) # arr[row, columns] => get me array of 0 and 1 rows with their column as 2 and 3
# Row 0 & 1 (0:2) , Col 0 , 1 , 2 (0:3)

Original 2d array:
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]
Multi-Dimensional Slicing operations
[[0 1]]


In [93]:
print(arr[0,2:4]) # slice first row , columns 2 & 3

[2 3]


In [39]:
# Iterating on numpy array
# for counter_variable in np.nditer(array):
#               print(counter_variable) 

import numpy as np

arr = np.arange(9).reshape(3,3)
print('Original array')
print('='*10)
print(arr)

print('Array elements are')
print('='*10)
# accessing each element of the array
for i in np.nditer(arr):
    print(i)

Original array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array elements are
0
1
2
3
4
5
6
7
8


### Array Manipulation

In [2]:
# Ravel example - converts 2D/3D array to 1D array
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr1 = arr1.ravel() # to convert a n-D array to 1-D array
print('After converting using ravel function')
print('='*10)
print(arr1)

[[1 2 3]
 [4 5 6]]
After converting using ravel function
[1 2 3 4 5 6]


In [42]:
# Transpose Example - inverts columns to rows

arr1 = np.array([[1,2,3],[4,5,6]])
print('\nOriginal array')
print('='*10)
print(arr1)
arr2 = np.transpose(arr1)

print('After converting using transpose function')
print('='*10)
print(arr2)


Original array
[[1 2 3]
 [4 5 6]]
After converting using transpose function
[[1 4]
 [2 5]
 [3 6]]


In [3]:
# Joining arrays

# Using Concatenate function - Both arrays want to concatenate must be of the same dimensions

import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[8, 10]])

print("arr1: ", arr1)
print("\n")
print("arr2: ", arr2)


print("row wise addition with another array - rowwise cat")
print(np.concatenate((arr1, arr2))) # by default axis = 0 is considered
print('*'*20)
print(np.concatenate((arr1, arr2.T), axis = 1)) # same as above statement

arr1:  [[1 2]
 [3 4]]


arr2:  [[ 8 10]]
row wise addition with another array - rowwise cat
[[ 1  2]
 [ 3  4]
 [ 8 10]]
********************
[[ 1  2  8]
 [ 3  4 10]]


In [44]:
print("column wise addition with another array - columnwise cat")
print(np.concatenate((arr1.T, arr2.T), axis = 1))

column wise addition with another array - columnwise cat
[[ 1  3  8]
 [ 2  4 10]]


In [45]:
print("None returns the multi-dimensional array in 1D array:")
print(np.concatenate((arr1, arr2), axis = None))

None returns the multi-dimensional array in 1D array:
[ 1  2  3  4  8 10]


In [46]:
# Joining arrays using stack, column_stack, hstack and vstack
# Self Explainatory on Slide...62, 63

### splitting arrays - split(), hsplit() and vsplit()

In [4]:
arr = np.array([10,20,30,40,50,60,70,80])
# indexes        0  1  2  3  4  5  6  7

print('\nOriginal array')
print(arr)
print('Array split')
print(np.split(arr, 4)) # splits the array into four subarrays of equal dimensions


Original array
[10 20 30 40 50 60 70 80]
Array split
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])]


In [5]:
arr1,arr2,arr3,arr4 = np.split(arr, 4)
arr1[1]

20

In [8]:
type(arr2)

numpy.ndarray

In [9]:
arr2[0]

30

In [50]:
arr3

array([50, 60])

In [51]:
arr4

array([70, 80])

In [11]:
# splits the array based on list of indices provided
b,c = np.split(arr, 2)
b

array([10, 20, 30, 40])

In [13]:
c

array([50, 60, 70, 80])

In [12]:
c[2]

70

In [54]:
# splitting arrays - split(), hsplit() and vsplit()

arr = np.arange(16).reshape(4,4)
print('\nOriginal array')
print(arr)
print('Array split using hsplit')
print(np.hsplit(arr, 4)) # splits the array into multiple sub-arrays horizontally (column wise)


Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Array split using hsplit
[array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [14]:
# splitting arrays - split(), hsplit() and vsplit()
arr = np.arange(16).reshape(4,4)
print('\nOriginal array')
print(arr)
print("\n")
print('Array split using vsplit') 
print(np.vsplit(arr,2)) # splits the array into multiple sub-arrays vertically (row wise)
print("\n")
arr_out = np.vsplit(arr,2)
print(arr_out)


Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Array split using vsplit
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


### File operations in numpy

In [15]:
import numpy as np

arr = np.arange(10)
print(arr)

fp = open('file_bin.npy', 'wb+')
np.save(fp, arr) # save the numpy array into file_bin.npy file 

[0 1 2 3 4 5 6 7 8 9]


In [16]:
fp = open('file_bin.npy', 'rb+')
fp.seek(0)
arr = np.load(fp) # loads the file
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr[0]

0

In [21]:
# File operations in numpy

import numpy as np

arr = np.arange(16).reshape(4,4)
print(arr)
print("\n")
np.savetxt('file_2.txt', arr, delimiter = ':', fmt='%0.1f') # save the numpy array into file_2.txt file 
# %d is used so that only decimal part is written to the file.


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]




In [22]:
fp = open("file_2.txt", 'r')# open file in read mode
  
print("the file contains:")
print(fp.read())

the file contains:
0:1:2:3
4:5:6:7
8:9:10:11
12:13:14:15

