In [17]:
import pandas as pd
from scipy.stats import ttest_ind, ttest_ind_from_stats
import numpy as np
import pandas as pd
from scipy import stats

In [18]:
df=pd.read_csv('T-test.csv')
df

Low_Light  High_Light
0         49          45
1         31          40
2         43          59
3         31          58
4         40          55
5         44          50
6         49          46
7         48          53
8         33          43

In [19]:
var1=df['Low_Light'].values
var2=df['High_Light'].values


In [20]:
print(var1)
print(var2)

[49 31 43 31 40 44 49 48 33]
[45 40 59 58 55 50 46 53 43]


In [21]:
t, p = ttest_ind(var1, var2, equal_var=False)
print("ttest_ind:            t = %g  p = %g" % (t, p))

ttest_ind:            t = -2.66075  p = 0.0172063


In [22]:
df=pd.read_csv("fish.csv")
print(df)

var1=df['food 1'].values
var2=df['food 2'].values
var3=df['food 3'].values
var4=df['food 4'].values

   food 1  food 2  food 3  food 4
0    60.8    68.7   102.6    87.9
1    57.0    67.7   102.1    84.2
2    65.0    74.0   100.2    83.1
3    58.6    66.3    96.5    85.7
4    61.7    69.8     NaN    90.3


In [23]:
print(var1)
print(var2)
print(var3)
print(var4)

[60.8 57.  65.  58.6 61.7]
[68.7 67.7 74.  66.3 69.8]
[102.6 102.1 100.2  96.5   nan]
[87.9 84.2 83.1 85.7 90.3]


In [24]:
v1=np.array(var1)
v2=np.array(var2)
v3=np.array(var3)
v4=np.array(var3)

In [25]:

print(stats.f_oneway(v1, v2, v3, v4))

F_onewayResult(statistic=nan, pvalue=nan)


In [26]:
food1 = np.array([ 31, 32, 53 ])
food2 = np.array([ 79, 48, 49 ])
food3= np.array([ 55, 46, 45])

print(stats.f_oneway(food1, food2, food3))

F_onewayResult(statistic=1.8181818181818181, pvalue=0.24138718539465462)
