In [1]:
import numpy as np

In [2]:
np.array([3.2,4,6,5])

array([3.2, 4. , 6. , 5. ])

In [3]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([1,2,3,4], dtype="str")

array(['1', '2', '3', '4'], dtype='<U1')

In [5]:
np.array([3,6,2,3], dtype="float32")

array([3., 6., 2., 3.], dtype=float32)

In [6]:
# nested lists result in multidimensional arrays
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype="int") 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((5,6), dtype="float")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5), dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))

array([[0.00992107, 0.67076956, 0.04421497],
       [0.23234412, 0.47075113, 0.56981686],
       [0.95932445, 0.89849035, 0.25559712]])

In [14]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[-0.80035734,  1.07799797, -0.65189175],
       [ 1.19473846,  0.00658418, -0.47658747],
       [ 1.42078519, -0.84380976, -0.48338057]])

In [15]:
# Create a 3x3 array of random integers in the interval [0, 10)

np.random.randint(0,10,(3,3))

array([[9, 2, 6],
       [2, 2, 3],
       [3, 3, 4]])

In [16]:
# Create a 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Return a new array of given shape and type, with random values

np.empty((3,3),dtype="int")

array([[4607182418800017408,                   0,                   0],
       [                  0, 4607182418800017408,                   0],
       [                  0,                   0, 4607182418800017408]])

In [18]:
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [19]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
#NumPy Array Attributes
#We'll use NumPy's random number generator, which we will seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) #it's same ((np.random.randint((0,10), size=6))) # One-dimensional array
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3,4,5)) # Three-dimensional array

print("x1 ndim: ",x1.ndim)
print("x1 shape: ",x1.shape)
print("x1 size: ",x1.size) #totaly,6 elements

print("x1 ndim: ",x2.ndim)
print("x1 shape: ",x2.shape)
print("x1 size: ",x2.size) #totaly,12 elements

print("x1 ndim: ",x3.ndim)
print("x1 shape: ",x3.shape)
print("x1 size: ",x3.size)#totaly,60 elements

print("dtype: ",x1.dtype) #the data type of the array
# Other attributes include itemsize, which lists the size (in bytes) of each array element,
# and nbytes, which lists the total size (in bytes) of the array:
print("itemsize:",x1.itemsize,"bytes")
print("nbytes:",x1.nbytes,"bytes")

print("dtype: ",x2.dtype) #the data type of the array
print("itemsize:",x2.itemsize,"bytes")
print("nbytes:",x2.nbytes,"bytes")

print("dtype: ",x3.dtype) #the data type of the array
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes") 

#In general, we expect that nbytes is equal to itemsize times size.

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x1 ndim:  2
x1 shape:  (3, 4)
x1 size:  12
x1 ndim:  3
x1 shape:  (3, 4, 5)
x1 size:  60
dtype:  int64
itemsize: 8 bytes
nbytes: 48 bytes
dtype:  int64
itemsize: 8 bytes
nbytes: 96 bytes
dtype:  int64
itemsize: 8 bytes
nbytes: 480 bytes


In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [33]:
x1[0]

5

In [34]:
x1[-1]

9

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x2[2,1]

6

In [37]:
grid = np.arange(1,10,1).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
x = np.array([1, 2, 3])
x.shape # x is a vector (3,)

(3,)

In [39]:
# row vector via reshape

x.reshape(1,3).shape

(1, 3)

In [40]:
# row vector via newaxis

x[np.newaxis, :].shape

(1, 3)

In [41]:
x.reshape(1,-1).shape

(1, 3)

In [42]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [43]:
# column vector via newaxis

x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [44]:
# NumPy's ufuncs feel very natural to use because they make use of Python's native
# arithmetic operators. The standard addition, subtraction, multiplication, and division
# can all be used:

x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [45]:
#There is also a unary ufunc for negation, a ** operator for exponentiation, and a %
#operator for modulus:

print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [46]:
# In addition, these can be strung together however you wish, and the standard order
# of operations is respected:

-(0.5*x+1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [47]:
# All of these arithmetic operations are simply convenient wrappers around specific
# functions built into NumPy; for example, the + operator is a wrapper for the add
# function:

print(np.add(3,2))

print(np.add(x,2)) #Addition +
print(np.subtract(x,5)) #Subtraction -
print(np.negative(x)) #Unary negation -
print(np.multiply(x,3)) #Multiplication *
print(np.divide(x,2)) #Division /
print(np.floor_divide(x,2)) #Floor division //
print(np.power(x,2)) #Exponentiation **
print(np.mod(x,2)) #Modulus/remainder **

print(np.multiply(x, x))

5
[2 3 4 5]
[-5 -4 -3 -2]
[ 0 -1 -2 -3]
[0 3 6 9]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 4 9]
[0 1 0 1]
[0 1 4 9]


In [48]:
# NumPy provides a large number of useful ufuncs, and some of the most useful for the
# data scientist are the trigonometric functions. We'll start by defining an array of
# angles:

theta = np.linspace(0,np.pi,3)


#Now we can compute some trigonometric fuctions on these values:
print("theta      =",theta)
print("sin(theta) =",np.sin(theta))
print("cos(theta) =",np.cos(theta))
print("tan(theta) =",np.tan(theta))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [49]:
x = [-1, 0, 1]

print("x = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [50]:
a = np.array([0,1,2])
b = np.array([5,5,5])
a+b

array([5, 6, 7])

In [51]:
# We can similarly extend this to arrays of higher dimension. Observe the result when
# we add a one-dimensional array to a two-dimensional array:

M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])